import { makeStyles } from "@mui/styles";
const useStyles = makeStyles((theme) => ({
  parent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "50px",
    // paddingTop: "50px",
    backgroundColor: "#333333",
    // backgroundColor: "red",
    // height: "200px",
  },
  child1: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    width: "300px",
    height: "300px",
    // border: "1px solid red",
    gap: "20px",
    padding: "50px",
    // paddingLeft: "50px",
    // paddingTop: "50px",
    // paddingRight: "50px",
  },
  phoneParent: {
    display: "flex",
    justifyContent: "space-between",
    width: "325px",
  },
  locationParent: {
    display: "flex",
    justifyContent: "space-between",
    width: "300px",
  },
  locationChild: {
    display: "flex",
    flexDirection: "column",
    width: "200px",
  },
  child2: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    width: "200px",
    height: "200px",
    gap: "5px",
    // backgroundColor: "red",
    marginBottom: "100px",
  },
  child3: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    width: "200px",
    height: "200px",
    gap: "5px",
    // backgroundColor: "red",
    marginBottom: "100px",
  },
  child4: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    // backgroundColor: "blue",
    width: "400px",
    height: "180px",
    marginBottom: "120px",
  },
  subscribeParent: {
    display: "flex",
    justifyContent: "space-between",
    width: "330px",
  },
  search: {
    display: "flex",
    alignItems: "center",
    width: "200px",

    height: "30px",
    backgroundColor: "#4c4c4c",
    paddingLeft: "20px",
  },
  subscribe: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100px",
    height: "30px",
    backgroundColor: "#00dc9a",
  },
  paymentParent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100vw",
    backgroundColor: "#2b2b2b",
    height: "50px",
    marginLeft: "10px",
    marginRight: "10px",
    // marginTop: "-10px",
    paddingLeft: "75px",
    paddingRight: "50px",
  },
}));
export default useStyles;
